/** Vietnamese UI copy. Song names and typing targets are not translated. */
import { STORY } from "./story";
import { viStory } from "./vi-story";
export const vi: Record<string, string> = {
  "Stillnote original": "Sáng tác gốc của Stillnote",
  "Korean traditional": "Dân gian Hàn Quốc",
  "Stillnote Encore — 3D game view": "Stillnote Encore — khung nhìn game 3D",
  "HIT STREAK": "LIÊN TIẾP",
  "KEEP GOING!": "TIẾP TỤC NÀO!",
  "NICE RHYTHM!": "ĐÚNG NHỊP LẮM!",
  "ON FIRE!": "BÙNG CHÁY!",
  "UNSTOPPABLE!": "KHÔNG THỂ CẢN!",
  "LEGENDARY!": "HUYỀN THOẠI!",
  relaxed: "thư thả",
  "the melody": "giai điệu",
  chords: "hợp âm",
  "The Hush's fog covers this island. Earn":
    "Sương mù của Hush bao phủ đảo này. Hãy giành",
  sources: "nguồn nhạc",
  "Unpacking the Encore…": "Đang chuẩn bị Encore…",
  "Painting the Sky Isles…": "Đang tô màu các đảo trên trời…",
  Ready: "Sẵn sàng",
  "Progress can't be saved in this browser (private mode?).":
    "Trình duyệt không thể lưu tiến trình (có thể do chế độ riêng tư).",
  "Progress reset. The Hush settles over the isles again…":
    "Đã xóa tiến trình. Hush lại bao phủ các hòn đảo…",
  "Piano samples couldn't load — using the synth piano.":
    "Không tải được âm thanh piano — đang dùng âm tổng hợp.",
  "is open! The Hush's fog lifts…": "đã mở! Sương mù của Hush đang tan…",
  "is ready to play.": "đã sẵn sàng để chơi.",
  "ENCORE ready — tap the gold button!": "ENCORE sẵn sàng — chạm nút vàng!",
  "ENCORE ready — press": "ENCORE sẵn sàng — nhấn",
  Space: "Space",
  "MIDI keyboard connected — try": "Đã kết nối đàn MIDI — thử chế độ",
  "keys!": "nhé!",
  "or the screen on each click…": "hoặc chạm màn hình theo từng tiếng nhịp…",
  "Timing offset set to": "Đã đặt bù độ trễ thành",
  "A synth lagoon where the lights went dark.":
    "Đầm nhạc điện tử đã tắt ánh đèn.",
  "The lighthouse that lost its tune.": "Ngọn hải đăng đánh mất giai điệu.",
  "Four isles, four seasons, one great wheel.":
    "Bốn đảo, bốn mùa, một vòng quay lớn.",
  "The Hush's castle above the clouds.":
    "Lâu đài của Hush trên những tầng mây.",
  "Open the classic piano studio instead": "Mở phòng đàn cổ điển",
  "Stillnote Encore needs WebGL 2, which this browser doesn't provide.":
    "Stillnote Encore cần WebGL 2, nhưng trình duyệt này không hỗ trợ.",
  "The Sky Isles couldn't load. Check your connection and reload.":
    "Không tải được các đảo. Hãy kiểm tra kết nối và tải lại.",
  "The Sky Isles couldn't start on this device.":
    "Không thể khởi động các đảo trên thiết bị này.",
  "Play the Silent Isles back to life":
    "Mang âm nhạc trở lại những hòn đảo tĩnh lặng",
  Play: "Chơi",
  Practice: "Luyện tập",
  Pause: "Tạm dừng",
  Paused: "Đã tạm dừng",
  Resume: "Tiếp tục",
  Restart: "Chơi lại",
  Retry: "Thử lại",
  "Back to map": "Về bản đồ",
  Settings: "Cài đặt",
  "Classic Studio": "Phòng đàn cổ điển",
  Songbook: "Thư viện nhạc",
  "Press any key · Headphones recommended":
    "Nhấn phím bất kỳ · Nên dùng tai nghe",
  Difficulty: "Độ khó",
  Easy: "Dễ",
  Normal: "Vừa",
  Hard: "Khó",
  Keys: "Phím chơi",
  Tap: "Chạm",
  Lanes: "Làn phím",
  "Real piano": "Piano thật",
  Words: "Gõ từ",
  "Left & right — made for phones": "Trái và phải — dành cho điện thoại",
  "Lanes follow the melody": "Các làn theo giai điệu",
  "Every key is the real note": "Mỗi phím là một nốt nhạc thật",
  "Type the words to the beat": "Gõ các từ tiếng Anh theo nhịp",
  "Keep the song playing": "Luôn phát bản nhạc",
  "— the music never stops; misses only show on screen.":
    "— nhạc luôn tiếp tục; nốt bỏ lỡ chỉ hiện trên màn hình.",
  "— the road waits for each note. No score, no stars.":
    "— chờ bạn chơi từng nốt. Không tính điểm hoặc sao.",
  "Practice speed": "Tốc độ luyện tập",
  "Not cleared yet at this setting.": "Chưa hoàn thành với thiết lập này.",
  "home-row words": "từ dùng hàng phím cơ sở",
  "everyday words": "từ thông dụng",
  "long words": "từ dài",
  "slow & roomy": "chậm và thoáng",
  "left & right": "trái và phải",
  "both sides at once": "hai bên cùng lúc",
  "split hands": "chia hai tay",
  "left hand": "tay trái",
  "right hand": "tay phải",
  "My songs": "Nhạc của tôi",
  "Import a song": "Nhập bản nhạc",
  "Import a MIDI or MusicXML file — Encore charts it for every difficulty. Files stay on this device and are kept until you close the page.":
    "Nhập tệp MIDI hoặc MusicXML — Encore tạo màn chơi cho mọi độ khó. Tệp chỉ ở trên thiết bị này và được giữ đến khi bạn đóng trang.",
  "Your own score, charted automatically.":
    "Bản nhạc của bạn, tự động tạo màn chơi.",
  Close: "Đóng",
  Back: "Quay lại",
  Skip: "Bỏ qua",
  Map: "Bản đồ",
  "Next stage": "Màn tiếp theo",
  "Practice complete": "Hoàn thành luyện tập",
  "Stage cleared!": "Đã vượt màn!",
  Results: "Kết quả",
  Score: "Điểm",
  SCORE: "ĐIỂM",
  Accuracy: "Độ chính xác",
  "Max combo": "Chuỗi dài nhất",
  Perfect: "Hoàn hảo",
  Great: "Rất tốt",
  Good: "Tốt",
  Miss: "Bỏ lỡ",
  "NEW BEST!": "KỶ LỤC MỚI!",
  "PERFECT!": "HOÀN HẢO!",
  GREAT: "RẤT TỐT",
  GOOD: "TỐT",
  MISS: "BỎ LỠ",
  EARLY: "SỚM",
  LATE: "MUỘN",
  HARMONY: "HÒA ÂM",
  COMBO: "CHUỖI",
  SPACE: "PHÍM CÁCH",
  TAP: "CHẠM",
  ENTER: "ENTER",
  "✗ WRONG KEY": "✗ SAI PHÍM",
  "Play!": "Chơi nào!",
  "Go!": "Bắt đầu!",
  Excerpt: "Trích đoạn",
  "Song keeps playing": "Nhạc luôn tiếp tục",
  "GOLDEN PHRASE! +ENCORE": "ĐOẠN NHẠC VÀNG! +ENCORE",
  "Golden phrase lost": "Đã lỡ đoạn nhạc vàng",
  "Note speed": "Tốc độ nốt",
  "Music volume": "Âm lượng nhạc",
  "Effects volume": "Âm lượng hiệu ứng",
  "Timing offset": "Bù độ trễ",
  "Calibrate timing": "Căn chỉnh độ trễ",
  "Tap along with 8 clicks; Encore sets the offset for your speakers and keyboard.":
    "Gõ theo 8 tiếng nhịp; Encore sẽ căn chỉnh độ trễ cho loa và bàn phím.",
  Graphics: "Đồ họa",
  Auto: "Tự động",
  Low: "Thấp",
  Medium: "Vừa",
  High: "Cao",
  Motion: "Chuyển động",
  "Follow system": "Theo hệ thống",
  Full: "Đầy đủ",
  Reduced: "Giảm chuyển động",
  "Lane keys": "Phím theo làn",
  "Laptop keys (real piano)": "Phím laptop (piano thật)",
  "Chromatic · A W S E D F T G…": "Bán cung · A W S E D F T G…",
  "Home row · A S D F / J K L ;": "Hàng cơ sở · A S D F / J K L ;",
  "D F J K · split hands": "D F J K · chia hai tay",
  "A S D F · left hand": "A S D F · tay trái",
  "J K L ; · right hand": "J K L ; · tay phải",
  "Note names on piano keys": "Tên nốt trên phím đàn",
  "Open all islands (free play)": "Mở mọi đảo (chơi tự do)",
  "Connect MIDI keyboard": "Kết nối đàn MIDI",
  "Plug in a USB/Bluetooth MIDI keyboard (Chrome, Edge).":
    "Kết nối đàn MIDI qua USB/Bluetooth (Chrome, Edge).",
  "Piano lacquer": "Màu đàn",
  Cherry: "Đỏ anh đào",
  Ocean: "Xanh đại dương",
  Sunflower: "Vàng hướng dương",
  Mint: "Xanh bạc hà",
  Grape: "Tím nho",
  Midnight: "Xanh đêm",
  "Reset progress": "Xóa tiến trình",
  "Reset all stars, scores and story progress? Settings are kept.":
    "Xóa toàn bộ sao, điểm và tiến trình cốt truyện? Cài đặt vẫn được giữ lại.",
  "Every island is open!": "Đã mở mọi hòn đảo!",
  "Full combo": "Chuỗi hoàn hảo",
  "Tuning the Encore…": "Đang lên dây Encore…",
  "Freeing the stillnotes…": "Đang giải phóng các nốt nhạc…",
  "Tuning the grand piano…": "Đang lên dây đại dương cầm…",
  "The orchestra is taking its seats…": "Dàn nhạc đang chuẩn bị…",
  "Right on the beat — great timing!": "Đúng nhịp — căn thời gian rất tốt!",
  "Not enough taps — try calibrating again.":
    "Chưa đủ lần gõ — hãy căn chỉnh lại.",
  "No MIDI keyboard found. Plug one in and try again.":
    "Chưa tìm thấy đàn MIDI. Hãy kết nối rồi thử lại.",
  "Dawn Meadow": "Đồng cỏ bình minh",
  "Starlight Snow Village": "Làng tuyết ánh sao",
  "Festival Hills": "Đồi lễ hội",
  "Ragtime Pier": "Bến cảng Ragtime",
  "Glasshouse Gardens": "Vườn nhà kính",
  "Neon Reef": "Rạn san hô neon",
  "Moonlit Harbour": "Bến cảng trăng",
  "Season Wheel": "Vòng quay bốn mùa",
  "Carillon Crown": "Vương miện chuông",
  "Where the first note wakes up.": "Nơi nốt nhạc đầu tiên thức giấc.",
  "Warm windows, frozen carols.": "Ô cửa ấm áp, những khúc hát đóng băng.",
  "A thousand lanterns waiting for a song.":
    "Ngàn chiếc đèn lồng đang chờ một khúc nhạc.",
  "The carnival that forgot how to swing.":
    "Lễ hội đã quên cách đung đưa theo nhạc.",
  "A conservatory of sleeping flowers.": "Nhà kính với những bông hoa say ngủ.",
};
for (const [trigger, lines] of Object.entries(STORY))
  lines.forEach((line, index) => {
    if (viStory[trigger]?.[index]) vi[line.text] = viStory[trigger][index];
  });
